/*
 * Copyright (C) 2008-12  Bernhard Hobiger
 *
 * This file is part of HoDoKu.
 *
 * HoDoKu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HoDoKu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HoDoKu. If not, see <http://www.gnu.org/licenses/>.
 */
package sudoku;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

/**
 *
 * @author  hobiwan
 */
public class ConfigColorPanel extends JPanel {
    private static final long serialVersionUID = 1L;

    private JButton[] buttons = null;
    private Color[] colors = null;

    /** Creates new form ConfigColorPanel */
    public ConfigColorPanel() {
        initComponents();

        buttons = new JButton[]{
            frameStrongButton, frameWeakButton, cluesButton, valuesButton,
            candidatesButton, invalidFGButton, wrongButton, normalBGButton,
            cursorBGButton, invalidBGButton, validBGButton,
            normalHintFGButton, normalHintBGButton, delHintFGButton,
            delHintBGButton, finsHintFGButton, finsHintBGButton,
            endoFinsHintFGButton, endoFinsHintBGButton, cannibalisticHintFGButton,
            cannibalisticHintBGButton, arrowButton, alsHintFGButton1, alsHintBGButton1,
            alsHintFGButton2, alsHintBGButton2, alsHintFGButton3, alsHintBGButton3,
            alsHintFGButton4, alsHintBGButton4, stiftButtona, stiftButtonA,
            stiftButtonb, stiftButtonB, stiftButtonc, stiftButtonC,
            stiftButtond, stiftButtonD, stiftButtone, stiftButtonE,
            alternateBGButton
        };

        initAll(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        frameAndDigitsPanel = new JPanel();
        frameLabel = new JLabel();
        cluesLabel = new JLabel();
        valuesLabel = new JLabel();
        candidatesLabel = new JLabel();
        invalidFGLabel = new JLabel();
        wrongLabel = new JLabel();
        frameStrongButton = new JButton();
        frameWeakButton = new JButton();
        cluesButton = new JButton();
        valuesButton = new JButton();
        candidatesButton = new JButton();
        invalidFGButton = new JButton();
        wrongButton = new JButton();
        backGroundPanel = new JPanel();
        normalBGLabel = new JLabel();
        cursorBGLabel = new JLabel();
        invalidBGLabel = new JLabel();
        validBGLabel = new JLabel();
        normalBGButton = new JButton();
        cursorBGButton = new JButton();
        invalidBGButton = new JButton();
        validBGButton = new JButton();
        alsLabel4 = new JLabel();
        alsHintFGButton4 = new JButton();
        alsHintBGButton4 = new JButton();
        alsHintBGButton3 = new JButton();
        alsHintFGButton3 = new JButton();
        alsLabel3 = new JLabel();
        alsLabel2 = new JLabel();
        alsHintFGButton2 = new JButton();
        alsHintBGButton2 = new JButton();
        alsHintBGButton1 = new JButton();
        alsHintFGButton1 = new JButton();
        alsLabel1 = new JLabel();
        alternateBGLabel = new JLabel();
        alternateBGButton = new JButton();
        jPanel2 = new JPanel();
        hintPanel = new JPanel();
        normHintBGLabel = new JLabel();
        delHintBGLabel = new JLabel();
        finsHintBGLabel = new JLabel();
        endoFinsHintBGLabel = new JLabel();
        cannibalisticHintBGLabel = new JLabel();
        arrowLabel = new JLabel();
        normalHintFGButton = new JButton();
        delHintFGButton = new JButton();
        finsHintFGButton = new JButton();
        endoFinsHintFGButton = new JButton();
        cannibalisticHintFGButton = new JButton();
        arrowButton = new JButton();
        normalHintBGButton = new JButton();
        delHintBGButton = new JButton();
        finsHintBGButton = new JButton();
        endoFinsHintBGButton = new JButton();
        cannibalisticHintBGButton = new JButton();
        coloringPanel = new JPanel();
        stiftLabelA = new JLabel();
        stiftButtona = new JButton();
        stiftButtonA = new JButton();
        stiftButtonB = new JButton();
        stiftButtonb = new JButton();
        stiftLabelB = new JLabel();
        stiftLabelC = new JLabel();
        stiftButtonc = new JButton();
        stiftButtonC = new JButton();
        stiftButtonD = new JButton();
        stiftButtond = new JButton();
        stiftLabelD = new JLabel();
        stiftLabelE = new JLabel();
        stiftButtone = new JButton();
        stiftButtonE = new JButton();
        resetButton = new JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("main/resources/intl/ConfigColorPanel"); // NOI18N
        frameAndDigitsPanel.setBorder(BorderFactory.createTitledBorder(bundle.getString("ConfigColorPanel.frameAndDigitsPanel.border.title"))); // NOI18N

        frameLabel.setText(bundle.getString("ConfigColorPanel.frameLabel.text")); // NOI18N

        cluesLabel.setText(bundle.getString("ConfigColorPanel.cluesLabel.text")); // NOI18N

        valuesLabel.setText(bundle.getString("ConfigColorPanel.valuesLabel.text")); // NOI18N

        candidatesLabel.setText(bundle.getString("ConfigColorPanel.candidatesLabel.text")); // NOI18N

        invalidFGLabel.setText(bundle.getString("ConfigColorPanel.invalidFGLabel.text")); // NOI18N

        wrongLabel.setText(bundle.getString("ConfigColorPanel.wrongLabel.text")); // NOI18N

        frameStrongButton.setText("..."); // NOI18N
        frameStrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameStrongButtonActionPerformed(evt);
            }
        });

        frameWeakButton.setText("..."); // NOI18N
        frameWeakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameWeakButtonActionPerformed(evt);
            }
        });

        cluesButton.setText("..."); // NOI18N
        cluesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cluesButtonActionPerformed(evt);
            }
        });

        valuesButton.setText("..."); // NOI18N
        valuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valuesButtonActionPerformed(evt);
            }
        });

        candidatesButton.setText("..."); // NOI18N
        candidatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatesButtonActionPerformed(evt);
            }
        });

        invalidFGButton.setText("..."); // NOI18N
        invalidFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invalidFGButtonActionPerformed(evt);
            }
        });

        wrongButton.setText("..."); // NOI18N
        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongButtonActionPerformed(evt);
            }
        });

        GroupLayout frameAndDigitsPanelLayout = new GroupLayout(frameAndDigitsPanel);
        frameAndDigitsPanel.setLayout(frameAndDigitsPanelLayout);
        frameAndDigitsPanelLayout.setHorizontalGroup(
            frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(frameAndDigitsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(frameLabel)
                    .addComponent(cluesLabel)
                    .addComponent(valuesLabel)
                    .addComponent(candidatesLabel)
                    .addComponent(invalidFGLabel)
                    .addComponent(wrongLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(frameAndDigitsPanelLayout.createSequentialGroup()
                        .addComponent(frameStrongButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frameWeakButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addComponent(cluesButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(valuesButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidatesButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalidFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        frameAndDigitsPanelLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {candidatesButton, cluesButton, frameWeakButton, invalidFGButton, valuesButton, wrongButton});

        frameAndDigitsPanelLayout.setVerticalGroup(
            frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(frameAndDigitsPanelLayout.createSequentialGroup()
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(frameLabel)
                    .addComponent(frameWeakButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(frameStrongButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cluesLabel)
                    .addComponent(cluesButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(valuesLabel)
                    .addComponent(valuesButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatesLabel)
                    .addComponent(candidatesButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(invalidFGLabel)
                    .addComponent(invalidFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAndDigitsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongLabel)
                    .addComponent(wrongButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backGroundPanel.setBorder(BorderFactory.createTitledBorder(null, bundle.getString("ConfigColorPanel.backGroundPanel.border.title"))); // NOI18N

        normalBGLabel.setText(bundle.getString("ConfigColorPanel.normalBGLabel.text")); // NOI18N

        cursorBGLabel.setText(bundle.getString("ConfigColorPanel.cursorBGLabel.text")); // NOI18N

        invalidBGLabel.setText(bundle.getString("ConfigColorPanel.invalidBGLabel.text")); // NOI18N

        validBGLabel.setText(bundle.getString("ConfigColorPanel.validBGLabel.text")); // NOI18N

        normalBGButton.setText("..."); // NOI18N
        normalBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalBGButtonActionPerformed(evt);
            }
        });

        cursorBGButton.setText("..."); // NOI18N
        cursorBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorBGButtonActionPerformed(evt);
            }
        });

        invalidBGButton.setText("..."); // NOI18N
        invalidBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invalidBGButtonActionPerformed(evt);
            }
        });

        validBGButton.setText("..."); // NOI18N
        validBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validBGButtonActionPerformed(evt);
            }
        });

        alsLabel4.setText(bundle.getString("ConfigColorPanel.alsLabel4.text")); // NOI18N

        alsHintFGButton4.setText("..."); // NOI18N
        alsHintFGButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintFGButton4ActionPerformed(evt);
            }
        });

        alsHintBGButton4.setText("..."); // NOI18N
        alsHintBGButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintBGButton4ActionPerformed(evt);
            }
        });

        alsHintBGButton3.setText("..."); // NOI18N
        alsHintBGButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintBGButton3ActionPerformed(evt);
            }
        });

        alsHintFGButton3.setText("..."); // NOI18N
        alsHintFGButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintFGButton3ActionPerformed(evt);
            }
        });

        alsLabel3.setText(bundle.getString("ConfigColorPanel.alsLabel3.text")); // NOI18N

        alsLabel2.setText(bundle.getString("ConfigColorPanel.alsLabel2.text")); // NOI18N

        alsHintFGButton2.setText("..."); // NOI18N
        alsHintFGButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintFGButton2ActionPerformed(evt);
            }
        });

        alsHintBGButton2.setText("..."); // NOI18N
        alsHintBGButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintBGButton2ActionPerformed(evt);
            }
        });

        alsHintBGButton1.setText("..."); // NOI18N
        alsHintBGButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintBGButton1ActionPerformed(evt);
            }
        });

        alsHintFGButton1.setText("..."); // NOI18N
        alsHintFGButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alsHintFGButton1ActionPerformed(evt);
            }
        });

        alsLabel1.setText(bundle.getString("ConfigColorPanel.alsLabel1.text")); // NOI18N

        alternateBGLabel.setText(bundle.getString("ConfigColorPanel.alternateBGLabel.text")); // NOI18N

        alternateBGButton.setText("..."); // NOI18N
        alternateBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternateBGButtonActionPerformed(evt);
            }
        });

        GroupLayout backGroundPanelLayout = new GroupLayout(backGroundPanel);
        backGroundPanel.setLayout(backGroundPanelLayout);
        backGroundPanelLayout.setHorizontalGroup(
            backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPanelLayout.createSequentialGroup()
                .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(normalBGLabel)
                    .addComponent(validBGLabel)
                    .addComponent(invalidBGLabel)
                    .addComponent(cursorBGLabel)
                    .addComponent(alternateBGLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(alternateBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(validBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalidBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursorBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundPanelLayout.createSequentialGroup()
                        .addComponent(alsLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alsHintFGButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alsHintBGButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundPanelLayout.createSequentialGroup()
                        .addComponent(alsLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alsHintFGButton4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alsHintBGButton4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundPanelLayout.createSequentialGroup()
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(alsLabel2)
                            .addComponent(alsLabel3))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundPanelLayout.createSequentialGroup()
                                .addComponent(alsHintFGButton2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alsHintBGButton2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGroup(backGroundPanelLayout.createSequentialGroup()
                                .addComponent(alsHintFGButton3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alsHintBGButton3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        backGroundPanelLayout.setVerticalGroup(
            backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPanelLayout.createSequentialGroup()
                .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundPanelLayout.createSequentialGroup()
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(normalBGLabel)
                            .addComponent(normalBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(cursorBGLabel)
                            .addComponent(cursorBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(invalidBGLabel)
                            .addComponent(invalidBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(validBGLabel)
                            .addComponent(validBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backGroundPanelLayout.createSequentialGroup()
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(alsLabel1)
                            .addComponent(alsHintFGButton1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                            .addComponent(alsHintBGButton1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(alsLabel2)
                            .addComponent(alsHintFGButton2, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                            .addComponent(alsHintBGButton2, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(alsLabel3)
                            .addComponent(alsHintBGButton3, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                            .addComponent(alsHintFGButton3, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(alsLabel4)
                            .addComponent(alsHintFGButton4, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                            .addComponent(alsHintBGButton4, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backGroundPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(alternateBGLabel)
                    .addComponent(alternateBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(backGroundPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frameAndDigitsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {backGroundPanel, frameAndDigitsPanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameAndDigitsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backGroundPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        hintPanel.setBorder(BorderFactory.createTitledBorder(bundle.getString("ConfigColorPanel.hintPanel.border.title"))); // NOI18N

        normHintBGLabel.setText(bundle.getString("ConfigColorPanel.normHintBGLabel.text")); // NOI18N

        delHintBGLabel.setText(bundle.getString("ConfigColorPanel.delHintBGLabel.text")); // NOI18N

        finsHintBGLabel.setText(bundle.getString("ConfigColorPanel.finsHintBGLabel.text")); // NOI18N

        endoFinsHintBGLabel.setText(bundle.getString("ConfigColorPanel.endoFinsHintBGLabel.text")); // NOI18N

        cannibalisticHintBGLabel.setText(bundle.getString("ConfigColorPanel.cannibalisticHintBGLabel.text")); // NOI18N

        arrowLabel.setText(bundle.getString("ConfigColorPanel.arrowLabel.text")); // NOI18N

        normalHintFGButton.setText("..."); // NOI18N
        normalHintFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalHintFGButtonActionPerformed(evt);
            }
        });

        delHintFGButton.setText("..."); // NOI18N
        delHintFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHintFGButtonActionPerformed(evt);
            }
        });

        finsHintFGButton.setText("..."); // NOI18N
        finsHintFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finsHintFGButtonActionPerformed(evt);
            }
        });

        endoFinsHintFGButton.setText("..."); // NOI18N
        endoFinsHintFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endoFinsHintFGButtonActionPerformed(evt);
            }
        });

        cannibalisticHintFGButton.setText("..."); // NOI18N
        cannibalisticHintFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cannibalisticHintFGButtonActionPerformed(evt);
            }
        });

        arrowButton.setText("..."); // NOI18N
        arrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowButtonActionPerformed(evt);
            }
        });

        normalHintBGButton.setText("..."); // NOI18N
        normalHintBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalHintBGButtonActionPerformed(evt);
            }
        });

        delHintBGButton.setText("..."); // NOI18N
        delHintBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHintBGButtonActionPerformed(evt);
            }
        });

        finsHintBGButton.setText("..."); // NOI18N
        finsHintBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finsHintBGButtonActionPerformed(evt);
            }
        });

        endoFinsHintBGButton.setText("..."); // NOI18N
        endoFinsHintBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endoFinsHintBGButtonActionPerformed(evt);
            }
        });

        cannibalisticHintBGButton.setText("..."); // NOI18N
        cannibalisticHintBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cannibalisticHintBGButtonActionPerformed(evt);
            }
        });

        GroupLayout hintPanelLayout = new GroupLayout(hintPanel);
        hintPanel.setLayout(hintPanelLayout);
        hintPanelLayout.setHorizontalGroup(
            hintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(hintPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(normHintBGLabel)
                    .addComponent(delHintBGLabel)
                    .addComponent(finsHintBGLabel)
                    .addComponent(endoFinsHintBGLabel)
                    .addComponent(cannibalisticHintBGLabel)
                    .addComponent(arrowLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(arrowButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addGroup(hintPanelLayout.createSequentialGroup()
                        .addComponent(cannibalisticHintFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cannibalisticHintBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(hintPanelLayout.createSequentialGroup()
                        .addComponent(endoFinsHintFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endoFinsHintBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(hintPanelLayout.createSequentialGroup()
                        .addComponent(finsHintFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finsHintBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(hintPanelLayout.createSequentialGroup()
                        .addComponent(delHintFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delHintBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(hintPanelLayout.createSequentialGroup()
                        .addComponent(normalHintFGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(normalHintBGButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        hintPanelLayout.setVerticalGroup(
            hintPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(hintPanelLayout.createSequentialGroup()
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(normHintBGLabel)
                    .addComponent(normalHintFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalHintBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(delHintBGLabel)
                    .addComponent(delHintFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(delHintBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(finsHintBGLabel)
                    .addComponent(finsHintFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(finsHintBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(endoFinsHintBGLabel)
                    .addComponent(endoFinsHintFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(endoFinsHintBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cannibalisticHintBGLabel)
                    .addComponent(cannibalisticHintFGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cannibalisticHintBGButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hintPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(arrowLabel)
                    .addComponent(arrowButton, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coloringPanel.setBorder(BorderFactory.createTitledBorder(bundle.getString("ConfigColorPanel.coloringPanel.border.title"))); // NOI18N

        stiftLabelA.setText(bundle.getString("ConfigColorPanel.stiftLabelA.text")); // NOI18N

        stiftButtona.setText("..."); // NOI18N
        stiftButtona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonaActionPerformed(evt);
            }
        });

        stiftButtonA.setText("..."); // NOI18N
        stiftButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonAActionPerformed(evt);
            }
        });

        stiftButtonB.setText("..."); // NOI18N
        stiftButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonBActionPerformed(evt);
            }
        });

        stiftButtonb.setText("..."); // NOI18N
        stiftButtonb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonbActionPerformed(evt);
            }
        });

        stiftLabelB.setText(bundle.getString("ConfigColorPanel.stiftLabelB.text")); // NOI18N

        stiftLabelC.setText(bundle.getString("ConfigColorPanel.stiftLabelC.text")); // NOI18N

        stiftButtonc.setText("..."); // NOI18N
        stiftButtonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtoncActionPerformed(evt);
            }
        });

        stiftButtonC.setText("..."); // NOI18N
        stiftButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonCActionPerformed(evt);
            }
        });

        stiftButtonD.setText("..."); // NOI18N
        stiftButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonDActionPerformed(evt);
            }
        });

        stiftButtond.setText("..."); // NOI18N
        stiftButtond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtondActionPerformed(evt);
            }
        });

        stiftLabelD.setText(bundle.getString("ConfigColorPanel.stiftLabelD.text")); // NOI18N

        stiftLabelE.setText(bundle.getString("ConfigColorPanel.stiftLabelE.text")); // NOI18N

        stiftButtone.setText("..."); // NOI18N
        stiftButtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtoneActionPerformed(evt);
            }
        });

        stiftButtonE.setText("..."); // NOI18N
        stiftButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiftButtonEActionPerformed(evt);
            }
        });

        GroupLayout coloringPanelLayout = new GroupLayout(coloringPanel);
        coloringPanel.setLayout(coloringPanelLayout);
        coloringPanelLayout.setHorizontalGroup(
            coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(coloringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(coloringPanelLayout.createSequentialGroup()
                        .addComponent(stiftLabelA)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtona, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtonA, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(coloringPanelLayout.createSequentialGroup()
                        .addComponent(stiftLabelD)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtond, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtonD, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addGroup(coloringPanelLayout.createSequentialGroup()
                        .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(stiftLabelB)
                            .addComponent(stiftLabelC))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(coloringPanelLayout.createSequentialGroup()
                                .addComponent(stiftButtonb, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stiftButtonB, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                            .addGroup(coloringPanelLayout.createSequentialGroup()
                                .addComponent(stiftButtonc, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stiftButtonC, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(coloringPanelLayout.createSequentialGroup()
                        .addComponent(stiftLabelE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtone, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stiftButtonE, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        coloringPanelLayout.setVerticalGroup(
            coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(coloringPanelLayout.createSequentialGroup()
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stiftLabelA)
                    .addComponent(stiftButtona, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stiftButtonA, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stiftLabelB)
                    .addComponent(stiftButtonb, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stiftButtonB, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stiftLabelC)
                    .addComponent(stiftButtonC, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stiftButtonc, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stiftLabelD)
                    .addComponent(stiftButtond, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stiftButtonD, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(coloringPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stiftLabelE)
                    .addComponent(stiftButtone, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stiftButtonE, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        resetButton.setMnemonic(java.util.ResourceBundle.getBundle("main/resources/intl/ConfigColorPanel").getString("ConfigColorPanel.resetButton.mnemonic").charAt(0));
        resetButton.setText(bundle.getString("ConfigColorPanel.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);


        jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(
        jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
        .addGroup(
        jPanel2Layout.createSequentialGroup()
        .addContainerGap(141, Short.MAX_VALUE)
        .addComponent(resetButton)
        .addGap(10)
        )
        )
        .addGroup(
        jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
        .addGroup(
        jPanel2Layout.createSequentialGroup()
        .addComponent(coloringPanel, GroupLayout.DEFAULT_SIZE,
                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap()
        )
        .addGroup(
        jPanel2Layout.createSequentialGroup()
        .addComponent(hintPanel, GroupLayout.DEFAULT_SIZE,
                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap()
        )
        )
        );

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hintPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coloringPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        initAll(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void alsHintBGButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintBGButton4ActionPerformed
        chooseColor(29);
    }//GEN-LAST:event_alsHintBGButton4ActionPerformed

    private void alsHintFGButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintFGButton4ActionPerformed
        chooseColor(28);
    }//GEN-LAST:event_alsHintFGButton4ActionPerformed

    private void alsHintBGButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintBGButton3ActionPerformed
        chooseColor(27);
    }//GEN-LAST:event_alsHintBGButton3ActionPerformed

    private void alsHintFGButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintFGButton3ActionPerformed
        chooseColor(26);
    }//GEN-LAST:event_alsHintFGButton3ActionPerformed

    private void alsHintBGButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintBGButton2ActionPerformed
        chooseColor(25);
    }//GEN-LAST:event_alsHintBGButton2ActionPerformed

    private void alsHintFGButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintFGButton2ActionPerformed
        chooseColor(24);
    }//GEN-LAST:event_alsHintFGButton2ActionPerformed

    private void alsHintBGButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintBGButton1ActionPerformed
        chooseColor(23);
    }//GEN-LAST:event_alsHintBGButton1ActionPerformed

    private void alsHintFGButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alsHintFGButton1ActionPerformed
        chooseColor(22);
    }//GEN-LAST:event_alsHintFGButton1ActionPerformed

    private void cannibalisticHintBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cannibalisticHintBGButtonActionPerformed
        chooseColor(20);
    }//GEN-LAST:event_cannibalisticHintBGButtonActionPerformed

    private void endoFinsHintBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endoFinsHintBGButtonActionPerformed
        chooseColor(18);
    }//GEN-LAST:event_endoFinsHintBGButtonActionPerformed

    private void finsHintBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finsHintBGButtonActionPerformed
        chooseColor(16);
    }//GEN-LAST:event_finsHintBGButtonActionPerformed

    private void delHintBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHintBGButtonActionPerformed
        chooseColor(14);
    }//GEN-LAST:event_delHintBGButtonActionPerformed

    private void normalHintBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalHintBGButtonActionPerformed
        chooseColor(12);
    }//GEN-LAST:event_normalHintBGButtonActionPerformed

    private void arrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowButtonActionPerformed
        chooseColor(21);
    }//GEN-LAST:event_arrowButtonActionPerformed

    private void cannibalisticHintFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cannibalisticHintFGButtonActionPerformed
        chooseColor(19);
    }//GEN-LAST:event_cannibalisticHintFGButtonActionPerformed

    private void endoFinsHintFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endoFinsHintFGButtonActionPerformed
        chooseColor(17);
    }//GEN-LAST:event_endoFinsHintFGButtonActionPerformed

    private void finsHintFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finsHintFGButtonActionPerformed
        chooseColor(15);
    }//GEN-LAST:event_finsHintFGButtonActionPerformed

    private void delHintFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHintFGButtonActionPerformed
        chooseColor(13);
    }//GEN-LAST:event_delHintFGButtonActionPerformed

    private void normalHintFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalHintFGButtonActionPerformed
        chooseColor(11);
    }//GEN-LAST:event_normalHintFGButtonActionPerformed

    private void validBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validBGButtonActionPerformed
        chooseColor(10);
    }//GEN-LAST:event_validBGButtonActionPerformed

    private void invalidBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invalidBGButtonActionPerformed
        chooseColor(9);
    }//GEN-LAST:event_invalidBGButtonActionPerformed

    private void cursorBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursorBGButtonActionPerformed
        chooseColor(8);
    }//GEN-LAST:event_cursorBGButtonActionPerformed

    private void normalBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalBGButtonActionPerformed
        chooseColor(7);
    }//GEN-LAST:event_normalBGButtonActionPerformed

    private void wrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongButtonActionPerformed
        chooseColor(6);
    }//GEN-LAST:event_wrongButtonActionPerformed

    private void invalidFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invalidFGButtonActionPerformed
        chooseColor(5);
    }//GEN-LAST:event_invalidFGButtonActionPerformed

    private void candidatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatesButtonActionPerformed
        chooseColor(4);
    }//GEN-LAST:event_candidatesButtonActionPerformed

    private void valuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valuesButtonActionPerformed
        chooseColor(3);
    }//GEN-LAST:event_valuesButtonActionPerformed

    private void cluesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cluesButtonActionPerformed
        chooseColor(2);
    }//GEN-LAST:event_cluesButtonActionPerformed

    private void frameWeakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameWeakButtonActionPerformed
        chooseColor(1);
    }//GEN-LAST:event_frameWeakButtonActionPerformed

    private void frameStrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameStrongButtonActionPerformed
        chooseColor(0);
    }//GEN-LAST:event_frameStrongButtonActionPerformed

private void stiftButtonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonaActionPerformed
    chooseColor(30);
}//GEN-LAST:event_stiftButtonaActionPerformed

private void stiftButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonAActionPerformed
    chooseColor(31);
}//GEN-LAST:event_stiftButtonAActionPerformed

private void stiftButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonBActionPerformed
    chooseColor(33);
}//GEN-LAST:event_stiftButtonBActionPerformed

private void stiftButtonbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonbActionPerformed
    chooseColor(32);
}//GEN-LAST:event_stiftButtonbActionPerformed

private void stiftButtoncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtoncActionPerformed
    chooseColor(34);
}//GEN-LAST:event_stiftButtoncActionPerformed

private void stiftButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonCActionPerformed
    chooseColor(35);
}//GEN-LAST:event_stiftButtonCActionPerformed

private void stiftButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonDActionPerformed
    chooseColor(37);
}//GEN-LAST:event_stiftButtonDActionPerformed

private void stiftButtondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtondActionPerformed
    chooseColor(36);
}//GEN-LAST:event_stiftButtondActionPerformed

private void stiftButtoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtoneActionPerformed
    chooseColor(38);
}//GEN-LAST:event_stiftButtoneActionPerformed

private void stiftButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiftButtonEActionPerformed
    chooseColor(39);
}//GEN-LAST:event_stiftButtonEActionPerformed

    private void alternateBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternateBGButtonActionPerformed
        chooseColor(40);
    }//GEN-LAST:event_alternateBGButtonActionPerformed

    private void chooseColor(int index) {
        Color init = colors[index];
        Color color = JColorChooser.showDialog(this, java.util.ResourceBundle.getBundle("main/resources/intl/ConfigColorPanel").getString("ConfigColorPanel.choose_color"), init);
        if (color != null) {
            colors[index] = color;
            initButton(buttons[index], color);
        }
    }

    public void okPressed() {
        Options.getInstance().setGridColor(colors[0]);
        Options.getInstance().setInnerGridColor(colors[1]);
        Options.getInstance().setCellFixedValueColor(colors[2]);
        Options.getInstance().setCellValueColor(colors[3]);
        Options.getInstance().setCandidateColor(colors[4]);
        Options.getInstance().setWrongValueColor(colors[5]);
        Options.getInstance().setDeviationColor(colors[6]);
        Options.getInstance().setDefaultCellColor(colors[7]);
        Options.getInstance().setAktCellColor(colors[8]);
        Options.getInstance().setInvalidCellColor(colors[9]);
        Options.getInstance().setPossibleCellColor(colors[10]);
        Options.getInstance().setHintCandidateColor(colors[11]);
        Options.getInstance().setHintCandidateBackColor(colors[12]);
        Options.getInstance().setHintCandidateDeleteColor(colors[13]);
        Options.getInstance().setHintCandidateDeleteBackColor(colors[14]);
        Options.getInstance().setHintCandidateFinColor(colors[15]);
        Options.getInstance().setHintCandidateFinBackColor(colors[16]);
        Options.getInstance().setHintCandidateEndoFinColor(colors[17]);
        Options.getInstance().setHintCandidateEndoFinBackColor(colors[18]);
        Options.getInstance().setHintCandidateCannibalisticColor(colors[19]);
        Options.getInstance().setHintCandidateCannibalisticBackColor(colors[20]);
        Options.getInstance().setArrowColor(colors[21]);
        Options.getInstance().getHintCandidateAlsColors()[0] = colors[22];
        Options.getInstance().getHintCandidateAlsBackColors()[0] = colors[23];
        Options.getInstance().getHintCandidateAlsColors()[1] = colors[24];
        Options.getInstance().getHintCandidateAlsBackColors()[1] = colors[25];
        Options.getInstance().getHintCandidateAlsColors()[2] = colors[26];
        Options.getInstance().getHintCandidateAlsBackColors()[2] = colors[27];
        Options.getInstance().getHintCandidateAlsColors()[3] = colors[28];
        Options.getInstance().getHintCandidateAlsBackColors()[3] = colors[29];
        Options.getInstance().getColoringColors()[0] = colors[30];
        Options.getInstance().getColoringColors()[1] = colors[31];
        Options.getInstance().getColoringColors()[2] = colors[32];
        Options.getInstance().getColoringColors()[3] = colors[33];
        Options.getInstance().getColoringColors()[4] = colors[34];
        Options.getInstance().getColoringColors()[5] = colors[35];
        Options.getInstance().getColoringColors()[6] = colors[36];
        Options.getInstance().getColoringColors()[7] = colors[37];
        Options.getInstance().getColoringColors()[8] = colors[38];
        Options.getInstance().getColoringColors()[9] = colors[39];
        Options.getInstance().setAlternateCellColor(colors[40]);
    }

    private void initAll(boolean setDefault) {
        if (colors == null) {
            colors = new Color[buttons.length];
        }
        if (setDefault) {
            colors[0] = Options.GRID_COLOR;
            colors[1] = Options.INNER_GRID_COLOR;
            colors[2] = Options.CELL_FIXED_VALUE_COLOR;
            colors[3] = Options.CELL_VALUE_COLOR;
            colors[4] = Options.CANDIDATE_COLOR;
            colors[5] = Options.WRONG_VALUE_COLOR;
            colors[6] = Options.DEVIATION_COLOR;
            colors[7] = Options.DEFAULT_CELL_COLOR;
            colors[8] = Options.AKT_CELL_COLOR;
            colors[9] = Options.INVALID_CELL_COLOR;
            colors[10] = Options.POSSIBLE_CELL_COLOR;
            colors[11] = Options.HINT_CANDIDATE_COLOR;
            colors[12] = Options.HINT_CANDIDATE_BACK_COLOR;
            colors[13] = Options.HINT_CANDIDATE_DELETE_COLOR;
            colors[14] = Options.HINT_CANDIDATE_DELETE_BACK_COLOR;
            colors[15] = Options.HINT_CANDIDATE_FIN_COLOR;
            colors[16] = Options.HINT_CANDIDATE_FIN_BACK_COLOR;
            colors[17] = Options.HINT_CANDIDATE_ENDO_FIN_COLOR;
            colors[18] = Options.HINT_CANDIDATE_ENDO_FIN_BACK_COLOR;
            colors[19] = Options.HINT_CANDIDATE_CANNIBALISTIC_COLOR;
            colors[20] = Options.HINT_CANDIDATE_CANNIBALISTIC_BACK_COLOR;
            colors[21] = Options.ARROW_COLOR;
            colors[22] = Options.HINT_CANDIDATE_ALS_COLORS[0];
            colors[23] = Options.HINT_CANDIDATE_ALS_BACK_COLORS[0];
            colors[24] = Options.HINT_CANDIDATE_ALS_COLORS[1];
            colors[25] = Options.HINT_CANDIDATE_ALS_BACK_COLORS[1];
            colors[26] = Options.HINT_CANDIDATE_ALS_COLORS[2];
            colors[27] = Options.HINT_CANDIDATE_ALS_BACK_COLORS[2];
            colors[28] = Options.HINT_CANDIDATE_ALS_COLORS[3];
            colors[29] = Options.HINT_CANDIDATE_ALS_BACK_COLORS[3];
            colors[30] = Options.COLORING_COLORS[0];
            colors[31] = Options.COLORING_COLORS[1];
            colors[32] = Options.COLORING_COLORS[2];
            colors[33] = Options.COLORING_COLORS[3];
            colors[34] = Options.COLORING_COLORS[4];
            colors[35] = Options.COLORING_COLORS[5];
            colors[36] = Options.COLORING_COLORS[6];
            colors[37] = Options.COLORING_COLORS[7];
            colors[38] = Options.COLORING_COLORS[8];
            colors[39] = Options.COLORING_COLORS[9];
            colors[40] = Options.ALTERNATE_CELL_COLOR;
        } else {
            colors[0] = Options.getInstance().getGridColor();
            colors[1] = Options.getInstance().getInnerGridColor();
            colors[2] = Options.getInstance().getCellFixedValueColor();
            colors[3] = Options.getInstance().getCellValueColor();
            colors[4] = Options.getInstance().getCandidateColor();
            colors[5] = Options.getInstance().getWrongValueColor();
            colors[6] = Options.getInstance().getDeviationColor();
            colors[7] = Options.getInstance().getDefaultCellColor();
            colors[8] = Options.getInstance().getAktCellColor();
            colors[9] = Options.getInstance().getInvalidCellColor();
            colors[10] = Options.getInstance().getPossibleCellColor();
            colors[11] = Options.getInstance().getHintCandidateColor();
            colors[12] = Options.getInstance().getHintCandidateBackColor();
            colors[13] = Options.getInstance().getHintCandidateDeleteColor();
            colors[14] = Options.getInstance().getHintCandidateDeleteBackColor();
            colors[15] = Options.getInstance().getHintCandidateFinColor();
            colors[16] = Options.getInstance().getHintCandidateFinBackColor();
            colors[17] = Options.getInstance().getHintCandidateEndoFinColor();
            colors[18] = Options.getInstance().getHintCandidateEndoFinBackColor();
            colors[19] = Options.getInstance().getHintCandidateCannibalisticColor();
            colors[20] = Options.getInstance().getHintCandidateCannibalisticBackColor();
            colors[21] = Options.getInstance().getArrowColor();
            colors[22] = Options.getInstance().getHintCandidateAlsColors()[0];
            colors[23] = Options.getInstance().getHintCandidateAlsBackColors()[0];
            colors[24] = Options.getInstance().getHintCandidateAlsColors()[1];
            colors[25] = Options.getInstance().getHintCandidateAlsBackColors()[1];
            colors[26] = Options.getInstance().getHintCandidateAlsColors()[2];
            colors[27] = Options.getInstance().getHintCandidateAlsBackColors()[2];
            colors[28] = Options.getInstance().getHintCandidateAlsColors()[3];
            colors[29] = Options.getInstance().getHintCandidateAlsBackColors()[3];
            colors[30] = Options.getInstance().getColoringColors()[0];
            colors[31] = Options.getInstance().getColoringColors()[1];
            colors[32] = Options.getInstance().getColoringColors()[2];
            colors[33] = Options.getInstance().getColoringColors()[3];
            colors[34] = Options.getInstance().getColoringColors()[4];
            colors[35] = Options.getInstance().getColoringColors()[5];
            colors[36] = Options.getInstance().getColoringColors()[6];
            colors[37] = Options.getInstance().getColoringColors()[7];
            colors[38] = Options.getInstance().getColoringColors()[8];
            colors[39] = Options.getInstance().getColoringColors()[9];
            colors[40] = Options.getInstance().getAlternateCellColor();
        }

        for (int i = 0; i < buttons.length; i++) {
            initButton(buttons[i], colors[i]);
        }
    }

    private void initButton(JButton button, Color color) {
        //button.setText(" ");
        Image img = new BufferedImage(10, 10, BufferedImage.TYPE_INT_RGB);
        Graphics g = img.getGraphics();
        g.setColor(color);
        g.fillRect(0, 0, 10, 10);
        button.setIcon(new ImageIcon(img));
        if (UIManager.getLookAndFeel().getName().equals("CDE/Motif")) {
            button.setBackground(color);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton alsHintBGButton1;
    private JButton alsHintBGButton2;
    private JButton alsHintBGButton3;
    private JButton alsHintBGButton4;
    private JButton alsHintFGButton1;
    private JButton alsHintFGButton2;
    private JButton alsHintFGButton3;
    private JButton alsHintFGButton4;
    private JLabel alsLabel1;
    private JLabel alsLabel2;
    private JLabel alsLabel3;
    private JLabel alsLabel4;
    private JButton alternateBGButton;
    private JLabel alternateBGLabel;
    private JButton arrowButton;
    private JLabel arrowLabel;
    private JPanel backGroundPanel;
    private JButton candidatesButton;
    private JLabel candidatesLabel;
    private JButton cannibalisticHintBGButton;
    private JLabel cannibalisticHintBGLabel;
    private JButton cannibalisticHintFGButton;
    private JButton cluesButton;
    private JLabel cluesLabel;
    private JPanel coloringPanel;
    private JButton cursorBGButton;
    private JLabel cursorBGLabel;
    private JButton delHintBGButton;
    private JLabel delHintBGLabel;
    private JButton delHintFGButton;
    private JButton endoFinsHintBGButton;
    private JLabel endoFinsHintBGLabel;
    private JButton endoFinsHintFGButton;
    private JButton finsHintBGButton;
    private JLabel finsHintBGLabel;
    private JButton finsHintFGButton;
    private JPanel frameAndDigitsPanel;
    private JLabel frameLabel;
    private JButton frameStrongButton;
    private JButton frameWeakButton;
    private JPanel hintPanel;
    private JButton invalidBGButton;
    private JLabel invalidBGLabel;
    private JButton invalidFGButton;
    private JLabel invalidFGLabel;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JLabel normHintBGLabel;
    private JButton normalBGButton;
    private JLabel normalBGLabel;
    private JButton normalHintBGButton;
    private JButton normalHintFGButton;
    private JButton resetButton;
    private JButton stiftButtonA;
    private JButton stiftButtonB;
    private JButton stiftButtonC;
    private JButton stiftButtonD;
    private JButton stiftButtonE;
    private JButton stiftButtona;
    private JButton stiftButtonb;
    private JButton stiftButtonc;
    private JButton stiftButtond;
    private JButton stiftButtone;
    private JLabel stiftLabelA;
    private JLabel stiftLabelB;
    private JLabel stiftLabelC;
    private JLabel stiftLabelD;
    private JLabel stiftLabelE;
    private JButton validBGButton;
    private JLabel validBGLabel;
    private JButton valuesButton;
    private JLabel valuesLabel;
    private JButton wrongButton;
    private JLabel wrongLabel;
    // End of variables declaration//GEN-END:variables
}
